### ISSUE TITLE
Can't test USB stack disable on laptops

### ISSUE THREAD

**Issue by mkopec** [Dasharo/open-source-firmware-validation#182]
### Device

NovaCustom laptops

### RTE version

n/a - PiKVM

### Affected component(s) or functionality

Automated tests of USB stack options in the setup menu

### Brief summary

`USB stack disable` on laptops disables PiKVM keyboard input rendering the DUT inoperable

### How reproducible

Always

### How to reproduce

- Set `USB_STACK_SUPPORT` to `TRUE` in platform config
- Run `USS002.001 Disable USB stack (firmware)`

### Expected behavior

Tests complete

### Actual behavior

Tests stop working, need to walk up to DUT and re-enable USB stack

### Link to screenshots or logs

none

### Additional context

On platforms where USB stack is disabled by default, this also means we need to disable the `Reset to Default` tests too.

### Solutions you've tried

Current w/a: disable USB stack tests

**Comment by pkubaj** [comment]
From the discussion with @mkopec on Mattermost - this is not possible to fix in our test framework. Tests fail because we disable USB while being connected via USB - this is expected and correct. Since we can't solve this issue, the only way to go is a workaround:
1. Testing manually.
2. Connecting via something else than USB - UART or Thunderbolt.
