### ISSUE TITLE
TPMCMD tests trying to run during the reboot process then fail because the device was turned off

### ISSUE THREAD

**Issue by philipandag** [Dasharo/open-source-firmware-validation#500]
### Device

V540TND

### RTE version

--

### OSFV version

develop

### Affected component(s) or functionality

TPMCMD automatic tests

### Brief summary

The test suite does not wait for the device to reboot and runs the tests immediately 

### How reproducible

100%

### How to reproduce

Run the whole TPCMD test suite

### Expected behavior

It should pass when run as a whole suite

### Actual behavior

The tests up to ~ TPCMD006.001 PASS, but then the device shuts down and all following tests fail.

### Link to screenshots or logs

[tpm2-commands.robot_log.zip](https://github.com/user-attachments/files/16975558/tpm2-commands.robot_log.zip)

### Additional context

Running the test cases individually works fine. When doing so the tests don't start until the device has rebooted completely  during suite setup, but if you run the suite as a whole the suite setup ends very quickly and the test cases start running, until the device reboots.

### Solutions you've tried

Running the test cases individually, I didn't find any issues with the test script at the first glance.

**Comment by wiktormowinski** [comment]
i was unable to replicate the issue. I guess the problem got solved somewhere along the wayby different issue.
i did the tests on 2 machines (one mentioned in issue) 2 times each with battery and power supply (because i suspected this my be the cause) the results...
[v560tnd.zip](https://github.com/user-attachments/files/17777228/v560tnd.zip)
[v560tnd-plugged.zip](https://github.com/user-attachments/files/17777256/v560tnd-plugged.zip)
[v540tnd.zip](https://github.com/user-attachments/files/17777292/v540tnd.zip)
[v540tnd-plugged.zip](https://github.com/user-attachments/files/17777377/v540tnd-plugged.zip)
...indicate the issue is no more.

@mkopec If there is anything else to check here, let me know.
